// 宇羲英文 Sight Word 字卡 — Lakeshore 300 Most Common Sight Words
// 分成六個等級，每級 50 個字
// Level 1: Words 1-50 (最常見)
// Level 2: Words 51-100
// Level 3: Words 101-150
// Level 4: Words 151-200
// Level 5: Words 201-250
// Level 6: Words 251-300

const SIGHT_WORDS = {
  "Level 1": [
    { word: "the", meaning: "這個", example: "The cat is big.", exampleMeaning: "這隻貓很大。" },
    { word: "of", meaning: "的；屬於", example: "A cup of water.", exampleMeaning: "一杯水。" },
    { word: "and", meaning: "和", example: "You and me.", exampleMeaning: "你和我。" },
    { word: "a", meaning: "一個", example: "I see a cat.", exampleMeaning: "我看到一隻貓。" },
    { word: "to", meaning: "到；去", example: "Go to school.", exampleMeaning: "去學校。" },
    { word: "in", meaning: "在⋯裡面", example: "The cat is in the box.", exampleMeaning: "貓在箱子裡面。" },
    { word: "is", meaning: "是", example: "This is fun.", exampleMeaning: "這很有趣。" },
    { word: "you", meaning: "你", example: "I love you!", exampleMeaning: "我愛你！" },
    { word: "that", meaning: "那個", example: "What is that?", exampleMeaning: "那是什麼？" },
    { word: "it", meaning: "它", example: "I like it.", exampleMeaning: "我喜歡它。" },
    { word: "he", meaning: "他", example: "He is my friend.", exampleMeaning: "他是我的朋友。" },
    { word: "was", meaning: "是（過去式）", example: "It was fun!", exampleMeaning: "那很好玩！" },
    { word: "for", meaning: "給；為了", example: "This is for you.", exampleMeaning: "這是給你的。" },
    { word: "on", meaning: "在⋯上面", example: "The book is on the table.", exampleMeaning: "書在桌子上。" },
    { word: "are", meaning: "是（複數）", example: "You are nice.", exampleMeaning: "你很好。" },
    { word: "as", meaning: "像⋯一樣", example: "Fast as a rabbit.", exampleMeaning: "像兔子一樣快。" },
    { word: "with", meaning: "和⋯一起", example: "Come with me.", exampleMeaning: "跟我來。" },
    { word: "his", meaning: "他的", example: "His bag is red.", exampleMeaning: "他的書包是紅色的。" },
    { word: "they", meaning: "他們", example: "They are playing.", exampleMeaning: "他們在玩。" },
    { word: "I", meaning: "我", example: "I am happy.", exampleMeaning: "我很開心。" },
    { word: "at", meaning: "在", example: "Look at the bird.", exampleMeaning: "看那隻鳥。" },
    { word: "be", meaning: "是；成為", example: "Be a good boy.", exampleMeaning: "做個好孩子。" },
    { word: "this", meaning: "這個", example: "I like this book.", exampleMeaning: "我喜歡這本書。" },
    { word: "have", meaning: "有", example: "I have a pet.", exampleMeaning: "我有一隻寵物。" },
    { word: "from", meaning: "從", example: "I am from Taiwan.", exampleMeaning: "我來自台灣。" },
    { word: "or", meaning: "或者", example: "Red or blue?", exampleMeaning: "紅色還是藍色？" },
    { word: "one", meaning: "一", example: "I have one apple.", exampleMeaning: "我有一顆蘋果。" },
    { word: "had", meaning: "有了（過去式）", example: "I had fun today.", exampleMeaning: "我今天玩得很開心。" },
    { word: "by", meaning: "在⋯旁邊", example: "Sit by me.", exampleMeaning: "坐在我旁邊。" },
    { word: "word", meaning: "字；單字", example: "Say the word.", exampleMeaning: "說出這個字。" },
    { word: "but", meaning: "但是", example: "I like cats, but not dogs.", exampleMeaning: "我喜歡貓，但不喜歡狗。" },
    { word: "not", meaning: "不", example: "I am not sad.", exampleMeaning: "我不難過。" },
    { word: "what", meaning: "什麼", example: "What is your name?", exampleMeaning: "你叫什麼名字？" },
    { word: "all", meaning: "全部", example: "We are all here.", exampleMeaning: "我們全部都在這裡。" },
    { word: "were", meaning: "是（過去複數）", example: "We were happy.", exampleMeaning: "我們很開心。" },
    { word: "we", meaning: "我們", example: "We are friends.", exampleMeaning: "我們是朋友。" },
    { word: "when", meaning: "什麼時候", example: "When is lunch?", exampleMeaning: "什麼時候吃午餐？" },
    { word: "your", meaning: "你的", example: "What is your name?", exampleMeaning: "你的名字是什麼？" },
    { word: "can", meaning: "可以；能", example: "I can run.", exampleMeaning: "我會跑。" },
    { word: "said", meaning: "說（過去式）", example: "Mom said yes.", exampleMeaning: "媽媽說好。" },
    { word: "there", meaning: "那裡", example: "Look over there.", exampleMeaning: "看那裡。" },
    { word: "use", meaning: "使用", example: "Use a pencil.", exampleMeaning: "用鉛筆。" },
    { word: "an", meaning: "一個（母音前）", example: "An orange.", exampleMeaning: "一顆柳丁。" },
    { word: "each", meaning: "每一個", example: "Each kid gets one.", exampleMeaning: "每個小孩拿一個。" },
    { word: "which", meaning: "哪一個", example: "Which one do you want?", exampleMeaning: "你想要哪一個？" },
    { word: "she", meaning: "她", example: "She is my sister.", exampleMeaning: "她是我的姐姐。" },
    { word: "do", meaning: "做", example: "What do you want?", exampleMeaning: "你想要什麼？" },
    { word: "how", meaning: "怎麼", example: "How are you?", exampleMeaning: "你好嗎？" },
    { word: "their", meaning: "他們的", example: "Their house is big.", exampleMeaning: "他們的房子很大。" },
    { word: "if", meaning: "如果", example: "If you are happy, smile!", exampleMeaning: "如果你開心，就笑吧！" }
  ],

  "Level 2": [
    { word: "will", meaning: "將會", example: "I will try!", exampleMeaning: "我會試試看！" },
    { word: "up", meaning: "上面", example: "Stand up!", exampleMeaning: "站起來！" },
    { word: "other", meaning: "其他的", example: "The other one is blue.", exampleMeaning: "另一個是藍色的。" },
    { word: "about", meaning: "關於", example: "Tell me about it.", exampleMeaning: "跟我說說。" },
    { word: "out", meaning: "外面", example: "Go out and play.", exampleMeaning: "出去玩。" },
    { word: "many", meaning: "許多", example: "I have many friends.", exampleMeaning: "我有很多朋友。" },
    { word: "then", meaning: "然後", example: "Eat, then play.", exampleMeaning: "吃完飯，然後去玩。" },
    { word: "them", meaning: "他們（受格）", example: "I like them.", exampleMeaning: "我喜歡他們。" },
    { word: "these", meaning: "這些", example: "I like these toys.", exampleMeaning: "我喜歡這些玩具。" },
    { word: "so", meaning: "所以", example: "I am tired, so I sleep.", exampleMeaning: "我累了，所以我睡覺。" },
    { word: "some", meaning: "一些", example: "I want some water.", exampleMeaning: "我想要一些水。" },
    { word: "her", meaning: "她的", example: "Her name is Lily.", exampleMeaning: "她的名字是莉莉。" },
    { word: "would", meaning: "會（語氣詞）", example: "Would you like a cookie?", exampleMeaning: "你想要一塊餅乾嗎？" },
    { word: "make", meaning: "做；製作", example: "Make a cake.", exampleMeaning: "做一個蛋糕。" },
    { word: "like", meaning: "喜歡", example: "I like ice cream.", exampleMeaning: "我喜歡冰淇淋。" },
    { word: "him", meaning: "他（受格）", example: "Give it to him.", exampleMeaning: "給他。" },
    { word: "into", meaning: "到⋯裡面", example: "Jump into the water.", exampleMeaning: "跳進水裡。" },
    { word: "time", meaning: "時間", example: "What time is it?", exampleMeaning: "現在幾點？" },
    { word: "has", meaning: "有（第三人稱）", example: "She has a dog.", exampleMeaning: "她有一隻狗。" },
    { word: "look", meaning: "看", example: "Look at me!", exampleMeaning: "看我！" },
    { word: "two", meaning: "二", example: "I have two hands.", exampleMeaning: "我有兩隻手。" },
    { word: "more", meaning: "更多", example: "I want more cake.", exampleMeaning: "我想要更多蛋糕。" },
    { word: "write", meaning: "寫", example: "Write your name.", exampleMeaning: "寫下你的名字。" },
    { word: "go", meaning: "去", example: "Let's go!", exampleMeaning: "我們走吧！" },
    { word: "see", meaning: "看到", example: "I see you!", exampleMeaning: "我看到你了！" },
    { word: "number", meaning: "數字", example: "Pick a number.", exampleMeaning: "選一個數字。" },
    { word: "no", meaning: "不", example: "No, thank you.", exampleMeaning: "不，謝謝。" },
    { word: "way", meaning: "路；方法", example: "This way, please.", exampleMeaning: "請這邊走。" },
    { word: "could", meaning: "可以（過去式）", example: "Could you help me?", exampleMeaning: "你可以幫我嗎？" },
    { word: "people", meaning: "人們", example: "Many people are here.", exampleMeaning: "很多人在這裡。" },
    { word: "my", meaning: "我的", example: "My name is Yu-Xi.", exampleMeaning: "我的名字是宇羲。" },
    { word: "than", meaning: "比", example: "I am taller than you.", exampleMeaning: "我比你高。" },
    { word: "first", meaning: "第一", example: "I am first!", exampleMeaning: "我是第一名！" },
    { word: "water", meaning: "水", example: "Drink some water.", exampleMeaning: "喝點水。" },
    { word: "been", meaning: "曾經是", example: "I have been there.", exampleMeaning: "我去過那裡。" },
    { word: "call", meaning: "叫；打電話", example: "Call your mom.", exampleMeaning: "打電話給你媽媽。" },
    { word: "who", meaning: "誰", example: "Who are you?", exampleMeaning: "你是誰？" },
    { word: "oil", meaning: "油", example: "Cook with oil.", exampleMeaning: "用油炒菜。" },
    { word: "now", meaning: "現在", example: "Do it now!", exampleMeaning: "現在就做！" },
    { word: "find", meaning: "找到", example: "Find the ball.", exampleMeaning: "找到球。" },
    { word: "long", meaning: "長的", example: "A long road.", exampleMeaning: "一條很長的路。" },
    { word: "down", meaning: "下面", example: "Sit down.", exampleMeaning: "坐下。" },
    { word: "day", meaning: "天", example: "Have a good day!", exampleMeaning: "祝你有美好的一天！" },
    { word: "did", meaning: "做了", example: "I did it!", exampleMeaning: "我做到了！" },
    { word: "get", meaning: "得到；拿", example: "Get the ball!", exampleMeaning: "拿到球！" },
    { word: "come", meaning: "來", example: "Come here!", exampleMeaning: "過來這裡！" },
    { word: "made", meaning: "做了（過去式）", example: "I made a cake.", exampleMeaning: "我做了一個蛋糕。" },
    { word: "may", meaning: "可以", example: "May I go out?", exampleMeaning: "我可以出去嗎？" },
    { word: "part", meaning: "部分", example: "This is part of the plan.", exampleMeaning: "這是計畫的一部分。" },
    { word: "over", meaning: "在⋯上方；結束", example: "Jump over the box.", exampleMeaning: "跳過箱子。" }
  ],

  "Level 3": [
    { word: "new", meaning: "新的", example: "I have new shoes.", exampleMeaning: "我有新鞋子。" },
    { word: "sound", meaning: "聲音", example: "What is that sound?", exampleMeaning: "那是什麼聲音？" },
    { word: "take", meaning: "拿；帶", example: "Take my hand.", exampleMeaning: "牽著我的手。" },
    { word: "only", meaning: "只有", example: "I have only one.", exampleMeaning: "我只有一個。" },
    { word: "little", meaning: "小的", example: "A little bird.", exampleMeaning: "一隻小鳥。" },
    { word: "work", meaning: "工作", example: "Let's get to work.", exampleMeaning: "我們開始工作吧。" },
    { word: "know", meaning: "知道", example: "I know the answer!", exampleMeaning: "我知道答案！" },
    { word: "place", meaning: "地方", example: "This is a nice place.", exampleMeaning: "這是一個好地方。" },
    { word: "year", meaning: "年", example: "Happy new year!", exampleMeaning: "新年快樂！" },
    { word: "live", meaning: "住；生活", example: "I live in Taipei.", exampleMeaning: "我住在台北。" },
    { word: "me", meaning: "我（受格）", example: "Give it to me.", exampleMeaning: "給我。" },
    { word: "back", meaning: "回來；背", example: "Come back soon.", exampleMeaning: "快點回來。" },
    { word: "give", meaning: "給", example: "Give me a hug.", exampleMeaning: "給我一個擁抱。" },
    { word: "most", meaning: "最多的", example: "I like this one the most.", exampleMeaning: "我最喜歡這個。" },
    { word: "very", meaning: "非常", example: "Very good!", exampleMeaning: "非常好！" },
    { word: "after", meaning: "在⋯之後", example: "After school, I play.", exampleMeaning: "放學後，我去玩。" },
    { word: "thing", meaning: "東西；事情", example: "What is this thing?", exampleMeaning: "這是什麼東西？" },
    { word: "our", meaning: "我們的", example: "This is our house.", exampleMeaning: "這是我們的房子。" },
    { word: "just", meaning: "只是；剛剛", example: "I just woke up.", exampleMeaning: "我剛剛醒來。" },
    { word: "name", meaning: "名字", example: "My name is Yu-Xi.", exampleMeaning: "我的名字是宇羲。" },
    { word: "good", meaning: "好的", example: "Good job!", exampleMeaning: "做得好！" },
    { word: "sentence", meaning: "句子", example: "Read the sentence.", exampleMeaning: "讀這個句子。" },
    { word: "man", meaning: "男人", example: "The man is tall.", exampleMeaning: "那個男人很高。" },
    { word: "think", meaning: "想；認為", example: "I think so.", exampleMeaning: "我覺得是這樣。" },
    { word: "say", meaning: "說", example: "Say hello!", exampleMeaning: "說你好！" },
    { word: "great", meaning: "很棒的", example: "That's great!", exampleMeaning: "太棒了！" },
    { word: "where", meaning: "哪裡", example: "Where is the cat?", exampleMeaning: "貓在哪裡？" },
    { word: "help", meaning: "幫忙", example: "Help me, please.", exampleMeaning: "請幫幫我。" },
    { word: "through", meaning: "穿過", example: "Walk through the door.", exampleMeaning: "走過那扇門。" },
    { word: "much", meaning: "很多（不可數）", example: "Thank you so much!", exampleMeaning: "非常謝謝你！" },
    { word: "before", meaning: "在⋯之前", example: "Wash hands before eating.", exampleMeaning: "吃飯前先洗手。" },
    { word: "line", meaning: "線；排隊", example: "Stand in line.", exampleMeaning: "排隊站好。" },
    { word: "right", meaning: "右邊；對的", example: "Turn right.", exampleMeaning: "右轉。" },
    { word: "too", meaning: "也；太", example: "I want to play too!", exampleMeaning: "我也想玩！" },
    { word: "mean", meaning: "意思是", example: "What does it mean?", exampleMeaning: "這是什麼意思？" },
    { word: "old", meaning: "老的；舊的", example: "An old tree.", exampleMeaning: "一棵老樹。" },
    { word: "any", meaning: "任何", example: "Do you have any pets?", exampleMeaning: "你有養寵物嗎？" },
    { word: "same", meaning: "相同的", example: "We have the same bag.", exampleMeaning: "我們有一樣的包包。" },
    { word: "tell", meaning: "告訴", example: "Tell me a story.", exampleMeaning: "跟我說一個故事。" },
    { word: "boy", meaning: "男孩", example: "The boy is running.", exampleMeaning: "那個男孩在跑。" },
    { word: "follow", meaning: "跟隨", example: "Follow me!", exampleMeaning: "跟我來！" },
    { word: "came", meaning: "來了", example: "She came home.", exampleMeaning: "她回家了。" },
    { word: "want", meaning: "想要", example: "I want a cookie.", exampleMeaning: "我想要一塊餅乾。" },
    { word: "show", meaning: "給⋯看", example: "Show me your drawing.", exampleMeaning: "給我看你的畫。" },
    { word: "also", meaning: "也", example: "I also like it.", exampleMeaning: "我也喜歡。" },
    { word: "around", meaning: "周圍", example: "Look around you.", exampleMeaning: "看看你的周圍。" },
    { word: "farm", meaning: "農場", example: "I live on a farm.", exampleMeaning: "我住在農場上。" },
    { word: "three", meaning: "三", example: "Three little pigs.", exampleMeaning: "三隻小豬。" },
    { word: "small", meaning: "小的", example: "A small cat.", exampleMeaning: "一隻小貓。" },
    { word: "set", meaning: "放置；一組", example: "Set the table.", exampleMeaning: "擺好桌子。" }
  ],

  "Level 4": [
    { word: "put", meaning: "放", example: "Put it down.", exampleMeaning: "放下來。" },
    { word: "end", meaning: "結束", example: "The story comes to an end.", exampleMeaning: "故事結束了。" },
    { word: "does", meaning: "做（第三人稱）", example: "She does her homework.", exampleMeaning: "她在做功課。" },
    { word: "another", meaning: "另一個", example: "I want another one.", exampleMeaning: "我想要另一個。" },
    { word: "well", meaning: "好地", example: "You did well!", exampleMeaning: "你做得很好！" },
    { word: "large", meaning: "大的", example: "A large pizza.", exampleMeaning: "一個大披薩。" },
    { word: "must", meaning: "必須", example: "You must be kind.", exampleMeaning: "你必須要善良。" },
    { word: "big", meaning: "大的", example: "A big dog.", exampleMeaning: "一隻大狗。" },
    { word: "even", meaning: "甚至", example: "Even I can do it!", exampleMeaning: "連我也做得到！" },
    { word: "such", meaning: "如此", example: "Such a nice day!", exampleMeaning: "多麼美好的一天！" },
    { word: "because", meaning: "因為", example: "I smile because I am happy.", exampleMeaning: "我笑是因為我開心。" },
    { word: "turn", meaning: "轉；輪到", example: "It's your turn.", exampleMeaning: "輪到你了。" },
    { word: "here", meaning: "這裡", example: "Come here.", exampleMeaning: "來這裡。" },
    { word: "why", meaning: "為什麼", example: "Why are you sad?", exampleMeaning: "你為什麼難過？" },
    { word: "ask", meaning: "問", example: "Ask your mom.", exampleMeaning: "問問你媽媽。" },
    { word: "went", meaning: "去了", example: "We went to the park.", exampleMeaning: "我們去了公園。" },
    { word: "men", meaning: "男人們", example: "The men are working.", exampleMeaning: "那些男人在工作。" },
    { word: "read", meaning: "讀", example: "Read a book.", exampleMeaning: "讀一本書。" },
    { word: "need", meaning: "需要", example: "I need your help.", exampleMeaning: "我需要你的幫忙。" },
    { word: "land", meaning: "土地", example: "The land is green.", exampleMeaning: "土地是綠色的。" },
    { word: "different", meaning: "不同的", example: "We are all different.", exampleMeaning: "我們都不一樣。" },
    { word: "home", meaning: "家", example: "I am going home.", exampleMeaning: "我要回家了。" },
    { word: "us", meaning: "我們（受格）", example: "Come with us.", exampleMeaning: "跟我們來。" },
    { word: "move", meaning: "移動", example: "Move your hands.", exampleMeaning: "動動你的手。" },
    { word: "try", meaning: "嘗試", example: "Try your best!", exampleMeaning: "盡力去做！" },
    { word: "kind", meaning: "善良的；種類", example: "Be kind to others.", exampleMeaning: "對別人善良。" },
    { word: "hand", meaning: "手", example: "Raise your hand.", exampleMeaning: "舉手。" },
    { word: "picture", meaning: "圖片", example: "Draw a picture.", exampleMeaning: "畫一張圖。" },
    { word: "again", meaning: "再一次", example: "Let's do it again!", exampleMeaning: "我們再做一次！" },
    { word: "change", meaning: "改變", example: "Change your clothes.", exampleMeaning: "換衣服。" },
    { word: "off", meaning: "關掉；離開", example: "Turn off the light.", exampleMeaning: "關燈。" },
    { word: "play", meaning: "玩", example: "Let's play!", exampleMeaning: "我們來玩吧！" },
    { word: "spell", meaning: "拼寫", example: "Spell your name.", exampleMeaning: "拼出你的名字。" },
    { word: "air", meaning: "空氣", example: "Fresh air feels good.", exampleMeaning: "新鮮空氣感覺很好。" },
    { word: "away", meaning: "離開", example: "Go away!", exampleMeaning: "走開！" },
    { word: "animal", meaning: "動物", example: "My favorite animal is a cat.", exampleMeaning: "我最喜歡的動物是貓。" },
    { word: "house", meaning: "房子", example: "A big house.", exampleMeaning: "一棟大房子。" },
    { word: "point", meaning: "指；點", example: "Point to the door.", exampleMeaning: "指向那扇門。" },
    { word: "page", meaning: "頁", example: "Turn the page.", exampleMeaning: "翻頁。" },
    { word: "letter", meaning: "字母；信", example: "Write a letter.", exampleMeaning: "寫一封信。" },
    { word: "mother", meaning: "媽媽", example: "I love my mother.", exampleMeaning: "我愛我的媽媽。" },
    { word: "answer", meaning: "回答", example: "Do you know the answer?", exampleMeaning: "你知道答案嗎？" },
    { word: "found", meaning: "找到了", example: "I found my toy!", exampleMeaning: "我找到我的玩具了！" },
    { word: "study", meaning: "學習", example: "I study every day.", exampleMeaning: "我每天學習。" },
    { word: "still", meaning: "仍然", example: "I am still here.", exampleMeaning: "我還在這裡。" },
    { word: "learn", meaning: "學習", example: "I want to learn.", exampleMeaning: "我想要學習。" },
    { word: "should", meaning: "應該", example: "You should try.", exampleMeaning: "你應該試試看。" },
    { word: "America", meaning: "美國", example: "America is far away.", exampleMeaning: "美國很遠。" },
    { word: "world", meaning: "世界", example: "The world is big.", exampleMeaning: "世界很大。" },
    { word: "high", meaning: "高的", example: "Jump up high!", exampleMeaning: "跳高高！" }
  ],

  "Level 5": [
    { word: "every", meaning: "每一個", example: "Every day is fun.", exampleMeaning: "每一天都很有趣。" },
    { word: "near", meaning: "靠近", example: "Come near me.", exampleMeaning: "靠近我。" },
    { word: "add", meaning: "加", example: "Add two and three.", exampleMeaning: "二加三。" },
    { word: "food", meaning: "食物", example: "The food is yummy.", exampleMeaning: "食物很好吃。" },
    { word: "between", meaning: "在⋯之間", example: "Sit between us.", exampleMeaning: "坐在我們中間。" },
    { word: "own", meaning: "自己的", example: "I have my own room.", exampleMeaning: "我有自己的房間。" },
    { word: "below", meaning: "在⋯下面", example: "Look below the table.", exampleMeaning: "看桌子下面。" },
    { word: "country", meaning: "國家", example: "Taiwan is a beautiful country.", exampleMeaning: "台灣是一個美麗的國家。" },
    { word: "plant", meaning: "植物；種植", example: "Plant a seed.", exampleMeaning: "種一顆種子。" },
    { word: "last", meaning: "最後的", example: "The last one wins.", exampleMeaning: "最後一個贏。" },
    { word: "school", meaning: "學校", example: "I go to school.", exampleMeaning: "我去上學。" },
    { word: "father", meaning: "爸爸", example: "My father is strong.", exampleMeaning: "我的爸爸很强壯。" },
    { word: "keep", meaning: "保持；保留", example: "Keep it clean.", exampleMeaning: "保持乾淨。" },
    { word: "tree", meaning: "樹", example: "A big tree.", exampleMeaning: "一棵大樹。" },
    { word: "never", meaning: "從不", example: "I will never give up.", exampleMeaning: "我永遠不放棄。" },
    { word: "start", meaning: "開始", example: "Let's start!", exampleMeaning: "開始吧！" },
    { word: "city", meaning: "城市", example: "The city is big.", exampleMeaning: "這個城市很大。" },
    { word: "earth", meaning: "地球", example: "We live on Earth.", exampleMeaning: "我們住在地球上。" },
    { word: "eye", meaning: "眼睛", example: "Close your eyes.", exampleMeaning: "閉上你的眼睛。" },
    { word: "light", meaning: "光；燈", example: "Turn on the light.", exampleMeaning: "開燈。" },
    { word: "thought", meaning: "想法；想了", example: "I thought about it.", exampleMeaning: "我想了一下。" },
    { word: "head", meaning: "頭", example: "Shake your head.", exampleMeaning: "搖搖你的頭。" },
    { word: "under", meaning: "在⋯下面", example: "The cat is under the bed.", exampleMeaning: "貓在床下面。" },
    { word: "story", meaning: "故事", example: "Tell me a story.", exampleMeaning: "跟我說一個故事。" },
    { word: "saw", meaning: "看到了", example: "I saw a rainbow.", exampleMeaning: "我看到一道彩虹。" },
    { word: "left", meaning: "左邊；離開了", example: "Turn left.", exampleMeaning: "左轉。" },
    { word: "don't", meaning: "不要", example: "Don't run!", exampleMeaning: "不要跑！" },
    { word: "few", meaning: "幾個", example: "A few more minutes.", exampleMeaning: "再幾分鐘。" },
    { word: "while", meaning: "一會兒", example: "Wait a while.", exampleMeaning: "等一下。" },
    { word: "along", meaning: "沿著", example: "Walk along the road.", exampleMeaning: "沿著路走。" },
    { word: "might", meaning: "可能", example: "It might rain today.", exampleMeaning: "今天可能會下雨。" },
    { word: "close", meaning: "關閉；靠近", example: "Close the door.", exampleMeaning: "關上門。" },
    { word: "something", meaning: "某個東西", example: "I see something!", exampleMeaning: "我看到了什麼東西！" },
    { word: "seem", meaning: "似乎", example: "You seem happy.", exampleMeaning: "你看起來很開心。" },
    { word: "next", meaning: "下一個", example: "What is next?", exampleMeaning: "接下來是什麼？" },
    { word: "hard", meaning: "困難的；硬的", example: "Don't give up, even if it's hard.", exampleMeaning: "就算很難也不要放棄。" },
    { word: "open", meaning: "打開", example: "Open the door.", exampleMeaning: "開門。" },
    { word: "example", meaning: "例子", example: "Here is an example.", exampleMeaning: "這是一個例子。" },
    { word: "begin", meaning: "開始", example: "Let's begin!", exampleMeaning: "我們開始吧！" },
    { word: "life", meaning: "生活；生命", example: "Life is beautiful.", exampleMeaning: "生活很美好。" },
    { word: "always", meaning: "總是", example: "I always try.", exampleMeaning: "我總是會試試看。" },
    { word: "those", meaning: "那些", example: "I like those shoes.", exampleMeaning: "我喜歡那些鞋子。" },
    { word: "both", meaning: "兩個都", example: "I like both of them.", exampleMeaning: "兩個我都喜歡。" },
    { word: "paper", meaning: "紙", example: "I need some paper.", exampleMeaning: "我需要一些紙。" },
    { word: "together", meaning: "一起", example: "Let's play together.", exampleMeaning: "我們一起玩吧。" },
    { word: "got", meaning: "得到了", example: "I got a star!", exampleMeaning: "我得到一顆星星！" },
    { word: "group", meaning: "一群", example: "A group of kids.", exampleMeaning: "一群小孩。" },
    { word: "often", meaning: "經常", example: "I often read books.", exampleMeaning: "我經常看書。" },
    { word: "run", meaning: "跑", example: "Run fast!", exampleMeaning: "跑快一點！" },
    { word: "important", meaning: "重要的", example: "This is important.", exampleMeaning: "這很重要。" }
  ],

  "Level 6": [
    { word: "until", meaning: "直到", example: "Wait until I come back.", exampleMeaning: "等到我回來。" },
    { word: "children", meaning: "孩子們", example: "The children are playing.", exampleMeaning: "孩子們在玩。" },
    { word: "side", meaning: "邊；旁邊", example: "Stand by my side.", exampleMeaning: "站在我旁邊。" },
    { word: "feet", meaning: "腳（複數）", example: "I have two feet.", exampleMeaning: "我有兩隻腳。" },
    { word: "car", meaning: "車子", example: "A red car.", exampleMeaning: "一輛紅色的車。" },
    { word: "miles", meaning: "英里", example: "It is two miles away.", exampleMeaning: "那裡有兩英里遠。" },
    { word: "night", meaning: "晚上", example: "Good night!", exampleMeaning: "晚安！" },
    { word: "walk", meaning: "走路", example: "Let's walk to school.", exampleMeaning: "我們走路去學校。" },
    { word: "white", meaning: "白色的", example: "A white rabbit.", exampleMeaning: "一隻白兔。" },
    { word: "sea", meaning: "海", example: "I see the sea!", exampleMeaning: "我看到海了！" },
    { word: "began", meaning: "開始了", example: "The show began.", exampleMeaning: "表演開始了。" },
    { word: "grow", meaning: "長大；成長", example: "Plants grow tall.", exampleMeaning: "植物長得很高。" },
    { word: "took", meaning: "拿了", example: "She took my hand.", exampleMeaning: "她牽了我的手。" },
    { word: "river", meaning: "河流", example: "A long river.", exampleMeaning: "一條長河。" },
    { word: "four", meaning: "四", example: "I have four toys.", exampleMeaning: "我有四個玩具。" },
    { word: "carry", meaning: "搬運；拿著", example: "Carry the bag.", exampleMeaning: "拿著這個包包。" },
    { word: "state", meaning: "州；狀態", example: "What state are you in?", exampleMeaning: "你在哪個州？" },
    { word: "once", meaning: "一次；曾經", example: "Once upon a time.", exampleMeaning: "從前從前。" },
    { word: "book", meaning: "書", example: "Read a book.", exampleMeaning: "讀一本書。" },
    { word: "hear", meaning: "聽到", example: "I hear a bird.", exampleMeaning: "我聽到一隻鳥叫。" },
    { word: "stop", meaning: "停止", example: "Stop running!", exampleMeaning: "不要跑了！" },
    { word: "without", meaning: "沒有", example: "Don't go without me.", exampleMeaning: "不要沒有我就走。" },
    { word: "second", meaning: "第二；秒", example: "I am second.", exampleMeaning: "我是第二名。" },
    { word: "late", meaning: "遲到的", example: "Don't be late!", exampleMeaning: "不要遲到！" },
    { word: "miss", meaning: "想念；錯過", example: "I miss you.", exampleMeaning: "我想念你。" },
    { word: "idea", meaning: "想法", example: "I have an idea!", exampleMeaning: "我有一個想法！" },
    { word: "enough", meaning: "足夠的", example: "That's enough.", exampleMeaning: "夠了。" },
    { word: "eat", meaning: "吃", example: "Let's eat lunch.", exampleMeaning: "我們吃午餐吧。" },
    { word: "face", meaning: "臉", example: "Wash your face.", exampleMeaning: "洗你的臉。" },
    { word: "watch", meaning: "看；手錶", example: "Watch this!", exampleMeaning: "看這個！" },
    { word: "far", meaning: "遠的", example: "How far is it?", exampleMeaning: "有多遠？" },
    { word: "Indian", meaning: "印度的", example: "Indian food is spicy.", exampleMeaning: "印度食物很辣。" },
    { word: "real", meaning: "真的", example: "Is it real?", exampleMeaning: "那是真的嗎？" },
    { word: "almost", meaning: "幾乎", example: "We are almost there.", exampleMeaning: "我們快到了。" },
    { word: "let", meaning: "讓", example: "Let me try.", exampleMeaning: "讓我試試。" },
    { word: "above", meaning: "在⋯上方", example: "The sky is above us.", exampleMeaning: "天空在我們上方。" },
    { word: "girl", meaning: "女孩", example: "The girl is dancing.", exampleMeaning: "那個女孩在跳舞。" },
    { word: "sometimes", meaning: "有時候", example: "Sometimes I feel happy.", exampleMeaning: "有時候我覺得很開心。" },
    { word: "mountain", meaning: "山", example: "A big mountain.", exampleMeaning: "一座大山。" },
    { word: "cut", meaning: "切；剪", example: "Cut the paper.", exampleMeaning: "剪紙。" },
    { word: "young", meaning: "年輕的", example: "A young boy.", exampleMeaning: "一個年輕的男孩。" },
    { word: "talk", meaning: "說話", example: "Let's talk.", exampleMeaning: "我們來聊聊。" },
    { word: "soon", meaning: "很快", example: "See you soon!", exampleMeaning: "很快再見！" },
    { word: "list", meaning: "清單", example: "Make a list.", exampleMeaning: "列一個清單。" },
    { word: "song", meaning: "歌", example: "Sing a song.", exampleMeaning: "唱一首歌。" },
    { word: "being", meaning: "存在；是", example: "Being kind is good.", exampleMeaning: "善良是好的。" },
    { word: "leave", meaning: "離開", example: "Time to leave.", exampleMeaning: "該離開了。" },
    { word: "family", meaning: "家人", example: "I love my family.", exampleMeaning: "我愛我的家人。" },
    { word: "it's", meaning: "它是；這是", example: "It's my turn!", exampleMeaning: "輪到我了！" },
    { word: "afternoon", meaning: "下午", example: "Good afternoon!", exampleMeaning: "午安！" }
  ]
};
